CREATE TABLE IF NOT EXISTS customer (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	entity_id BIGINT NOT NULL COMMENT '客户实体ID', 
	nick_name VARCHAR(64) NOT NULL COMMENT '昵称' DEFAULT '', 
	mobile VARCHAR(32) COMMENT '已验证手机号（含国家码）', 
	email VARCHAR(254) COMMENT '已验证邮箱', 
	gender SMALLINT NOT NULL COMMENT '0未知1男2女' DEFAULT 0, 
	birthday DATE COMMENT '生日', 
	country VARCHAR(64) NOT NULL COMMENT '国家' DEFAULT '', 
	province VARCHAR(64) NOT NULL COMMENT '省份' DEFAULT '', 
	city VARCHAR(64) NOT NULL COMMENT '城市' DEFAULT '', 
	personal_profile VARCHAR(255) NOT NULL COMMENT '个人简介' DEFAULT '', 
	status SMALLINT NOT NULL COMMENT '1正常2禁用3注销' DEFAULT 1, 
	register_source VARCHAR(32) NOT NULL COMMENT '注册来源' DEFAULT 'wechat_mp', 
	last_login_time DATETIME COMMENT '最后登录UTC时间', 
	last_login_ip VARCHAR(45) COMMENT '最后登录IP', 
	create_time DATETIME NOT NULL COMMENT '创建UTC时间' DEFAULT CURRENT_TIMESTAMP, 
	update_time DATETIME NOT NULL COMMENT '修改UTC时间' DEFAULT CURRENT_TIMESTAMP, 
	deleted_at DATETIME COMMENT '注销UTC时间', 
	PRIMARY KEY (id), 
	UNIQUE (entity_id), 
	UNIQUE (mobile), 
	UNIQUE (email),
	INDEX `ix_customer_status_created` (`status`, `create_time`)
)ENGINE=InnoDB CHARSET=utf8mb4;
